### ISSUE TITLE
Add confirmation requirement if leaving reward screen without taking all rewards

### ISSUE THREAD

**Issue by rilifon** [Space-Paca/alchemy-game#172]

**Comment by arthurtui** [comment]
What if instead we just automatically transmute all untaken reagents? We just need to think of reworking the flow so a player can't leave without getting a recipe hint.

**Comment by rilifon** [comment]
As a user pointed out in a comment (from that gameplay video), there might be players who are playing a challenge run like "never take gold", so to cater for all types of players it would be best if we don't force anything on the player. 
A simple confirmation should do the trick, and solves the other cases like not picking a hint too

**Comment by arthurtui** [comment]
Resolved with 6cc113a7fb507b035da63731c378275fe0b9f379
