### ISSUE TITLE
Implement events- Round 2

### ISSUE THREAD

**Issue by arthurtui** [Space-Paca/alchemy-game#18]
- [x] Push your luck

- [x] Desafio elite

- [x] Desafio normal

- [x] Desafio push your luck

- [x] Desafio boss

- [x] Moedas Amaldiçoadas

- [x] Equipamentos Amaldiçoados

- [x] Sacrificio de sangue

- [x] Fonte de sangue

- [x] Pacto de Sangue

- [x] Resting Place

- [x] Vida

**Comment by rilifon** [comment]
Three events were pushed to later:

- [ ] Artefatos por lixo

- [ ] Reagentes 1

- [ ] Receitas Épicas
